config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'search#search'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  resources :users, only: [:show,:index,:edit,:update] do
    member do
      get 'follower'
      get 'followed'
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.user_id = current_user.id
    @book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
<tr>
  <td>
    <%= link_to user_path(book.user) do %>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %><br>
      <%= book_comment.user.name %>
    <% end %>
  </td>
  <td><%= book_comment.comment %></td>
  <% if book_comment.user == current_user %>
  <td><%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, remote: true, class: "btn btn-sm btn-danger" %></td>
  <% end %>
</tr>
<% end %>

app/views/book_comments/create.js.erb
$('#comments-count_<%= @book.id %>').html("コメント数: <%= @book.book_comments.count %>");
$('.comments_area').html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$('#comments-count_<%= @book.id %>').html("コメント数: <%= @book.book_comments.count %>");
$('.comments_area').html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");